import type { Cookie } from "@/components/cookies/cookie-policy";

export const cookies: Cookie[] = [
  {
    name: "cookie_consent",
    provider: "Own",
    purpose: "Ukládá preference souhlasu s cookies.",
    duration: "1 rok",
    category: "essential",
    storageType: "cookie",
  },
  {
    name: "theme",
    provider: "Own",
    purpose: "Ukládá preferenci motivu (systémový/světlý/tmavý režim).",
    duration: "Trvalé",
    category: "functional",
    storageType: "localStorage",
  },
  {
    name: "consent_change_check",
    provider: "Own",
    purpose: "Sleduje změny souhlasu pro aktualizaci skriptů.",
    duration: "Relace",
    category: "functional",
    storageType: "sessionStorage",
  },
  {
    name: "_ga",
    provider: "Google Analytics",
    purpose: "Rozlišuje uživatele pro účely analýzy (se souhlasem).",
    duration: "2 roky",
    category: "analytics",
    storageType: "cookie",
  },
  {
    name: "_ga_*",
    provider: "Google Analytics",
    purpose: "Uchovává stav relace GA4 (se souhlasem).",
    duration: "2 roky",
    category: "analytics",
    storageType: "cookie",
  },
  {
    name: "_gid",
    provider: "Google Analytics",
    purpose: "Rozlišuje uživatele po dobu 24 hodin (se souhlasem).",
    duration: "24 hodin",
    category: "analytics",
    storageType: "cookie",
  },
  {
    name: "_gat",
    provider: "Google Analytics",
    purpose: "Omezuje četnost požadavků (se souhlasem).",
    duration: "1 minuta",
    category: "analytics",
    storageType: "cookie",
  },
  {
    name: "_gcl_au",
    provider: "Google Tag Manager",
    purpose: "Experimenty s efektivitou AdSense (se souhlasem).",
    duration: "3 měsíce",
    category: "analytics",
    storageType: "cookie",
  },
];
